# Generated by Django 4.0.5 on 2022-07-23 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='The title of this element', max_length=60, verbose_name='element')),
                ('body', models.TextField(blank=True, help_text='The body (using Markdown) of the element', verbose_name='body')),
                ('rank', models.IntegerField(help_text='The order on the list compared to siblings', verbose_name='rank')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ppclp.element')),
            ],
        ),
    ]
