# Generated by Django 4.0.5 on 2022-07-28 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='The name of the content block, seen only by editors', max_length=100, verbose_name='name')),
                ('content', models.TextField(blank=True, help_text='The content of the block', verbose_name='content')),
                ('date_modified', models.DateField(auto_now=True, help_text='The date of last modification')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the page', max_length=50, verbose_name='name')),
                ('slug', models.CharField(help_text='The URL slug', max_length=50, verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='The name of the element, seen only by editors', max_length=100, verbose_name='name')),
                ('header_text', models.CharField(blank=True, help_text='The text of the headline for this elememnt', max_length=100, null=True)),
                ('order', models.IntegerField(default=0, help_text='The order in which this element appears on the page', verbose_name='order')),
                ('level', models.IntegerField(default=0, help_text='The indentation level of this element', verbose_name='level')),
                ('content', models.ForeignKey(help_text='The content of this element', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ppclp.contentblock')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppclp.page')),
            ],
            options={
                'ordering': ['page', 'order', 'level', 'name'],
            },
        ),
    ]
