# Generated by Django 4.0.5 on 2022-07-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppclp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='date_modified',
            field=models.DateField(auto_now=True, help_text='The date of last modification'),
        ),
        migrations.AlterField(
            model_name='element',
            name='content',
            field=models.TextField(blank=True, default='', help_text='The content of the block', verbose_name='content'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ContentBlock',
        ),
    ]
