# Generated by Django 4.0.5 on 2022-07-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppclp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='element',
            name='title',
        ),
        migrations.AddField(
            model_name='element',
            name='indent',
            field=models.IntegerField(default=0, help_text='The indent level of this item', verbose_name='indent'),
        ),
        migrations.AddField(
            model_name='element',
            name='is_heading',
            field=models.BooleanField(default=0, help_text='If this is a heading or a paragraph', verbose_name='is heading'),
        ),
    ]
