# Generated by Django 4.0.5 on 2022-07-27 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppclp', '0002_remove_element_parent_remove_element_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the page', max_length=50, verbose_name='name')),
                ('slug', models.CharField(help_text='The URL slug', max_length=50, verbose_name='slug')),
            ],
        ),
        migrations.RemoveField(
            model_name='element',
            name='indent',
        ),
        migrations.RemoveField(
            model_name='element',
            name='rank',
        ),
        migrations.AddField(
            model_name='element',
            name='name',
            field=models.CharField(default='', help_text='The name - seen only by administrators', max_length=50, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ElementPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(help_text='The order on the page', verbose_name='rank')),
                ('indent', models.IntegerField(default=0, help_text='The indent level of this placement', verbose_name='indent')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppclp.element')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppclp.page')),
            ],
        ),
    ]
