# Generated by Django 4.0.5 on 2022-07-31 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppclp', '0003_rename_header_text_element_title_alter_element_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='element',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='element',
            name='level',
        ),
        migrations.RemoveField(
            model_name='element',
            name='name',
        ),
        migrations.RemoveField(
            model_name='element',
            name='order',
        ),
        migrations.RemoveField(
            model_name='element',
            name='page',
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='The order in which this element appears on the page', verbose_name='order')),
                ('level', models.PositiveSmallIntegerField(default=2, help_text='The heading level of this element, corresponding to the html tags &lt;h2&gt; - &lt;h6&gt;.  Note: The default is 2. &lt;h1&gt; is used for the page title', verbose_name='level')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppclp.element')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppclp.page')),
            ],
            options={
                'ordering': ['page', 'order'],
            },
        ),
    ]
