# Generated by Django 4.0.5 on 2022-07-31 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppclp', '0004_alter_element_options_alter_page_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='title',
            field=models.CharField(blank=True, default='', help_text='The text of the headline for this elememnt', max_length=100),
            preserve_default=False,
        ),
    ]
