# Generated by Django 4.0.5 on 2022-08-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppclp', '0005_alter_element_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='If this placement should not appear in the menubar or in the listing of all elements.', verbose_name='hidden'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='level',
            field=models.PositiveSmallIntegerField(default=2, help_text='The heading level of this element, corresponding to the html tags &lt;h2&gt; - &lt;h6&gt;.  Only use 2 - 6.  &lt;h1&gt; is used for the page title. ', verbose_name='level'),
        ),
    ]
