# Generated by Django 4.1 on 2022-08-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppclp', '0006_placement_is_hidden_alter_placement_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(2, 'h2'), (3, 'h3'), (4, 'h4'), (5, 'h5'), (6, 'h6')], default=2, help_text='The heading level of this element, corresponding to the html tags &lt;h2&gt; - &lt;h6&gt;.  Only use 2 - 6.  &lt;h1&gt; is used for the page title. ', verbose_name='level'),
        ),
    ]
