# Generated by Django 4.1 on 2022-08-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppclp', '0008_alter_page_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='cover_photo',
            field=models.ImageField(blank=True, help_text='The cover photo for this page', null=True, upload_to='', verbose_name='Cover Photo'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(help_text='The URL slug', unique=True, verbose_name='slug'),
        ),
    ]
